// Livros/livros-react/src/LivroLista.js
import React, { useState, useEffect } from "react";
import { ControleLivros } from "./controle/ControleLivros";
import { ControleEditora } from "./controle/ControleEditora";

const controleLivro = new ControleLivros();
const controleEditora = new ControleEditora();

const LinhaLivro = ({ livro, excluir, editar }) => {
  const nomeEditora = controleEditora.getNomeEditora(livro.codEditora);

  return (
    <tr>
      <td>
        <button
          className="btn btn-danger btn-sm me-2"
          onClick={() => excluir(livro.codigo)}
        >
          Excluir
        </button>
        <button
          className="btn btn-primary btn-sm"
          onClick={() => editar(livro)}
        >
          Editar
        </button>
      </td>
      <td>{livro.titulo}</td>
      <td>{livro.resumo}</td>
      <td>{nomeEditora}</td>
      <td>
        <ul>
          {livro.autores.map((autor, index) => (
            <li key={index}>{autor}</li>
          ))}
        </ul>
      </td>
    </tr>
  );
};

const LivroLista = () => {
  const [livros, setLivros] = useState([]);
  const [carregado, setCarregado] = useState(false);

  useEffect(() => {
    if (!carregado) {
      controleLivro.obterLivros().then(livrosObtidos => {
        setLivros(Array.isArray(livrosObtidos) ? livrosObtidos : []);
        setCarregado(true);
      });
    }
  }, [carregado]);

  const excluir = (codigo) => {
    controleLivro.excluir(codigo);
    setCarregado(false);
  };

  const editar = (livro) => {
    const novoTitulo = window.prompt('Novo título:', livro.titulo);
    if (novoTitulo && novoTitulo !== livro.titulo) {
      controleLivro.editar({ ...livro, titulo: novoTitulo }).then(() => setCarregado(false));
    }
  };

  return (
    <main className="container mt-4">
      <h1>Catálogo de Livros</h1>
      <table className="table table-striped table-bordered">
        <thead className="table-dark">
          <tr>
            <th>Ações</th>
            <th>Título</th>
            <th>Resumo</th>
            <th>Editora</th>
            <th>Autores</th>
          </tr>
        </thead>
        <tbody>
          {livros.map((livro) => (
            <LinhaLivro
              key={livro.codigo}
              livro={livro}
              excluir={excluir}
              editar={editar}
            />
          ))}
        </tbody>
      </table>
    </main>
  );
};

export default LivroLista;

// Livros/livros-angular/src/app/livro-lista/livro-lista.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';

import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';

import { Editora } from '../editora';
import { Livro } from '../livro';

@Component({
  selector: 'app-livro-lista',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './livro-lista.component.html',
  styleUrl: './livro-lista.component.css'
})
export class LivroListaComponent implements OnInit {
  public editoras: Array<Editora> = [];
  public livros: Array<Livro> = [];

  constructor(
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivrosService) { }

  ngOnInit() {
    this.editoras = this.servEditora.getEditoras();

    this.servLivros.obterLivros().then((livros: any[]) => {
      this.livros = livros.map(livro => ({
        codigo: livro.codigo ?? '', ...livro
      }));
    }).catch((error) => {
      console.error('Erro ao obter livros:', error);
    });
  }


  excluir(codigo: String) {
    this.servLivros.excluir(codigo).then(() => {
      return this.servLivros.obterLivros();
    }).then((livros: any[]) => {
      this.livros = livros.map(livro => ({
        codigo: livro.codigo ?? '', ...livro
      }));
    }).catch((error) => {
      console.error('Erro ao excluir ou obter livros:', error);
    });
  }

  obterNome = (codEditora: number): string => {
    return this.servEditora.getNomeEditora(codEditora);
  }
}

<main class="container mt-5">
  <h2 class="mb-4 text-center">Lista de Livros</h2>

  <table class="table table-striped table-bordered">
    <thead class="table-dark">
      <tr>
        <!-- <th scope="col">Código</th> -->
        <th scope="col">Título</th>
        <th scope="col">Resumo</th>
        <th scope="col">Editora</th>
        <th scope="col">Autores</th>
      </tr>
    </thead>
    <tbody>
      <tr *ngFor="let livro of livros">
        <!-- <td>{{ livro.codigo }}</td> -->
        <td style="font-weight: bold;">
          {{ livro.titulo }}
          <button class="btn btn-sm btn-danger ms-2" (click)="excluir(livro.codigo)">
            Excluir
          </button>
        </td>
        <td>{{ livro.resumo }}</td>
        <td>{{ obterNome(livro.codEditora) }}</td>
        <td>
          <ul class="mb-0">
            <li *ngFor="let autor of livro.autores">{{ autor }}</li>
          </ul>
        </td>
      </tr>
    </tbody>
  </table>
</main>
